"""empty message

Revision ID: 09aa18ab632e
Revises: e530c912a1f3
Create Date: 2023-05-07 19:12:43.212051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09aa18ab632e'
down_revision = 'e530c912a1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adds_ibfk_1', 'adds', type_='foreignkey')
    op.create_foreign_key(None, 'adds', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('attendance_ibfk_1', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('face_value_ibfk_1', 'face_value', type_='foreignkey')
    op.create_foreign_key(None, 'face_value', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('holiday_apply_ibfk_1', 'holiday_apply', type_='foreignkey')
    op.create_foreign_key(None, 'holiday_apply', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('holidays_ibfk_1', 'holidays', type_='foreignkey')
    op.create_foreign_key(None, 'holidays', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('outs_ibfk_1', 'outs', type_='foreignkey')
    op.create_foreign_key(None, 'outs', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('overtime_record_ibfk_1', 'overtime_record', type_='foreignkey')
    op.create_foreign_key(None, 'overtime_record', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('set_ibfk_1', 'set', type_='foreignkey')
    op.create_foreign_key(None, 'set', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.alter_column('staff_information', 'staffCheckState',
               existing_type=mysql.INTEGER(),
               comment='非工作时间：0  出勤：{普通出勤：10 , 出差：11 ,  休假： 12  , 加班出勤： 13} ;   缺勤：{普通缺勤：20 , 普通迟到：21 ;  普通早退：22;  加班缺勤：23  ;  加班迟到： 24 ;  加班早退： 25}',
               existing_comment='下班：0  出勤：{普通出勤：10 , 出差：11 , 休假：12} ;   缺勤：{普通缺勤：20 , 加班缺勤：21}',
               existing_nullable=True)
    op.drop_constraint('staff_information_ibfk_3', 'staff_information', type_='foreignkey')
    op.drop_constraint('staff_information_ibfk_1', 'staff_information', type_='foreignkey')
    op.drop_constraint('staff_information_ibfk_2', 'staff_information', type_='foreignkey')
    op.create_foreign_key(None, 'staff_information', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.create_foreign_key(None, 'staff_information', 'position', ['staffPositionId'], ['positionId'], onupdate='CASCADE')
    op.create_foreign_key(None, 'staff_information', 'departments', ['staffDepartmentId'], ['departmentId'], onupdate='CASCADE')
    op.drop_constraint('sum_ibfk_1', 'sum', type_='foreignkey')
    op.create_foreign_key(None, 'sum', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('system_apply_ibfk_1', 'system_apply', type_='foreignkey')
    op.create_foreign_key(None, 'system_apply', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    op.drop_constraint('works_ibfk_1', 'works', type_='foreignkey')
    op.create_foreign_key(None, 'works', 'staff', ['staffId'], ['staffId'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.create_foreign_key('works_ibfk_1', 'works', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'system_apply', type_='foreignkey')
    op.create_foreign_key('system_apply_ibfk_1', 'system_apply', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'sum', type_='foreignkey')
    op.create_foreign_key('sum_ibfk_1', 'sum', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'staff_information', type_='foreignkey')
    op.drop_constraint(None, 'staff_information', type_='foreignkey')
    op.drop_constraint(None, 'staff_information', type_='foreignkey')
    op.create_foreign_key('staff_information_ibfk_2', 'staff_information', 'position', ['staffPositionId'], ['positionId'])
    op.create_foreign_key('staff_information_ibfk_1', 'staff_information', 'staff', ['staffId'], ['staffId'])
    op.create_foreign_key('staff_information_ibfk_3', 'staff_information', 'departments', ['staffDepartmentId'], ['departmentId'])
    op.alter_column('staff_information', 'staffCheckState',
               existing_type=mysql.INTEGER(),
               comment='下班：0  出勤：{普通出勤：10 , 出差：11 , 休假：12} ;   缺勤：{普通缺勤：20 , 加班缺勤：21}',
               existing_comment='非工作时间：0  出勤：{普通出勤：10 , 出差：11 ,  休假： 12  , 加班出勤： 13} ;   缺勤：{普通缺勤：20 , 普通迟到：21 ;  普通早退：22;  加班缺勤：23  ;  加班迟到： 24 ;  加班早退： 25}',
               existing_nullable=True)
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.create_foreign_key('set_ibfk_1', 'set', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'overtime_record', type_='foreignkey')
    op.create_foreign_key('overtime_record_ibfk_1', 'overtime_record', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'outs', type_='foreignkey')
    op.create_foreign_key('outs_ibfk_1', 'outs', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'holidays', type_='foreignkey')
    op.create_foreign_key('holidays_ibfk_1', 'holidays', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'holiday_apply', type_='foreignkey')
    op.create_foreign_key('holiday_apply_ibfk_1', 'holiday_apply', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'face_value', type_='foreignkey')
    op.create_foreign_key('face_value_ibfk_1', 'face_value', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_ibfk_1', 'attendance', 'staff', ['staffId'], ['staffId'])
    op.drop_constraint(None, 'adds', type_='foreignkey')
    op.create_foreign_key('adds_ibfk_1', 'adds', 'staff', ['staffId'], ['staffId'])
    # ### end Alembic commands ###
