"""empty message

Revision ID: 0f3e7a295781
Revises: c5c28eda8e14
Create Date: 2023-04-16 20:59:45.641831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3e7a295781'
down_revision = 'c5c28eda8e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('staffAddress', sa.Text(), nullable=True, comment='家庭住址'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_information', 'staffAddress')
    # ### end Alembic commands ###
