"""empty message

Revision ID: 33396d2e8be1
Revises: d4f16b16efa0
Create Date: 2023-04-04 21:34:31.030988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33396d2e8be1'
down_revision = 'd4f16b16efa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('informationState', sa.Boolean(), nullable=False, comment='职工信息完善状态'))
    op.add_column('staff_information', sa.Column('faceValueState', sa.Boolean(), nullable=False, comment='职工人脸信息完善状态'))
    op.create_foreign_key(None, 'staff_information', 'departments', ['staffDepartmentId'], ['departmentId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_information', type_='foreignkey')
    op.drop_column('staff_information', 'faceValueState')
    op.drop_column('staff_information', 'informationState')
    # ### end Alembic commands ###
