"""empty message

Revision ID: 37c02e6bc8ad
Revises: d1256cb3bb09
Create Date: 2023-05-14 15:17:07.673500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c02e6bc8ad'
down_revision = 'd1256cb3bb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 外键、主键、非空、不重复'),
    sa.Column('attendTime', sa.DateTime(), server_default='1900-01-01 00:00:00', nullable=True, comment='应签到时间'),
    sa.Column('endTime', sa.DateTime(), nullable=True, comment='应签退时间', server_defalut='1900-01-01 00:00:00'),
    sa.Column('beginAttendDate', sa.Date(), nullable=True, comment='考勤起始日期', server_defalut='1900-01-01'),
    sa.Column('endAttendDate', sa.Date(), nullable=True, comment='考勤结束日期', server_defalut='1900-01-01'),
    sa.Column('holidayState', sa.Boolean(), server_default='0', nullable=True, comment='请假状态/默认没有请假FALSE/不能为空'),
    sa.Column('beginHolidayDate', sa.Date(), nullable=True, comment='请假起始日期'),
    sa.Column('endHolidayDate', sa.Date(), nullable=True, comment='请假结束日期'),
    sa.Column('outState', sa.Boolean(), server_default='0', nullable=True, comment='出差状态/默认没有出差FALSE/不能为空'),
    sa.Column('beginOutDate', sa.Date(), nullable=True, comment='出差起始日期'),
    sa.Column('endOutDate', sa.Date(), nullable=True, comment='出差结束日期'),
    sa.Column('addState', sa.Boolean(), server_default='0', nullable=True, comment='加班状态/默认没有加班FALSE/不能为空'),
    sa.Column('beginAddTime', sa.DateTime(), nullable=True, comment='加班起始具体时间（年月日时分秒）/ 不设置结束时间，以结束后打卡时间为准'),
    sa.Column('updateTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='设置更新时间'),
    sa.Column('updateId', sa.String(length=20), nullable=True, comment='更新者id'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set')
    # ### end Alembic commands ###
