"""empty message

Revision ID: 39ea1d6b586c
Revises: 
Create Date: 2023-05-18 17:09:26.909409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ea1d6b586c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.String(length=20), nullable=False, comment='系统管理员ID、主键、不为空、不重复'),
    sa.Column('adminPassWord', sa.String(length=20), server_default=sa.text("'123456'"), nullable=True, comment='系统管理员密码 不允许为空'),
    sa.Column('loginTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='上次登录时间'),
    sa.PrimaryKeyConstraint('adminId'),
    sa.UniqueConstraint('adminId')
    )
    op.create_table('attendance_aps',
    sa.Column('attendanceApsId', sa.String(length=20), nullable=False, comment='APS 函数ID/主键/非空/唯一值'),
    sa.Column('execute_time', sa.DateTime(), nullable=True, comment='上一次执行时间'),
    sa.PrimaryKeyConstraint('attendanceApsId'),
    sa.UniqueConstraint('attendanceApsId')
    )
    op.create_table('departments',
    sa.Column('departmentId', sa.String(length=20), nullable=False, comment='部门ID/主键/不为空/不重复'),
    sa.Column('departmentName', sa.String(length=20), nullable=False, comment='部门名称'),
    sa.PrimaryKeyConstraint('departmentId'),
    sa.UniqueConstraint('departmentId')
    )
    op.create_table('gate_admin',
    sa.Column('gateAdminId', sa.String(length=20), nullable=False),
    sa.Column('gateAdminPassWord', sa.String(length=20), server_default=sa.text("'123456'"), nullable=True),
    sa.Column('loginTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('gateAdminId'),
    sa.UniqueConstraint('gateAdminId')
    )
    op.create_table('position',
    sa.Column('positionId', sa.String(length=20), nullable=False, comment='岗位ID'),
    sa.Column('positionName', sa.String(length=20), nullable=True, comment='岗位名称'),
    sa.Column('positionLevel', sa.Integer(), nullable=True, comment='岗位等级'),
    sa.PrimaryKeyConstraint('positionId'),
    sa.UniqueConstraint('positionId'),
    sa.UniqueConstraint('positionName')
    )
    op.create_table('staff',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 主键、不允许为空、不重复'),
    sa.Column('staffPassWord', sa.String(length=20), server_default=sa.text("'123456'"), nullable=True, comment='职工密码 不为空'),
    sa.Column('loginTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='上次登录时间'),
    sa.Column('staffState', sa.Boolean(), server_default='1', nullable=True, comment='就职状态（默认设置为在职TRUE） 不为空'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('system_announcement',
    sa.Column('announcementId', sa.String(length=20), nullable=False, comment='公告记录ID/主键/不为空/不重复'),
    sa.Column('publishId', sa.String(length=20), nullable=True, comment='发布者ID'),
    sa.Column('publishTime', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('publishMessage', sa.Text(), nullable=True, comment='发布内容'),
    sa.PrimaryKeyConstraint('announcementId'),
    sa.UniqueConstraint('announcementId')
    )
    op.create_table('adds',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/主键/外键/不为空/不重复'),
    sa.Column('addState', sa.Boolean(), server_default='0', nullable=True, comment='加班状态'),
    sa.Column('addTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='加班总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('attendance',
    sa.Column('attendanceId', sa.String(length=50), nullable=False, comment='出勤记录ID/主键/不重复/不为空/！！以当天Date日期+职工ID合成String作为出勤记录ID存入！！'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/允许重复（1对多）/不为空'),
    sa.Column('attendTime', sa.Time(), nullable=True, comment='签到打卡时间'),
    sa.Column('endTime', sa.Time(), nullable=True, comment='签退打卡时间'),
    sa.Column('workTime', sa.Time(), nullable=True, comment='工作时间'),
    sa.Column('attendDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='记录日期'),
    sa.Column('attendImage', sa.LargeBinary(length=65536), nullable=True, comment='签到拍照打卡截图'),
    sa.Column('endImage', sa.LargeBinary(length=65536), nullable=True, comment='签退拍照打卡截图'),
    sa.Column('attendState', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='签到状态/默认为0未打卡/不为空/出勤1/迟到2/缺勤3'),
    sa.Column('endState', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='签退状态/默认为0未打卡/不为空/早退2/晚签退3'),
    sa.Column('outState', sa.Boolean(), server_default='0', nullable=True, comment='出差状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态,如果出差，在此记录状态，工作时间设置八小时，其余空白/出差总时长相应增加/出差次数+1'),
    sa.Column('holidayState', sa.Boolean(), server_default='0', nullable=True, comment='请假状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态 如果请假，在此记录状态，工作时间设置0，其余空白，请假次数+1/假期剩余总时长对应相减/'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('attendanceId'),
    sa.UniqueConstraint('attendanceId')
    )
    op.create_table('department_admin',
    sa.Column('departmentAdminId', sa.String(length=20), nullable=False),
    sa.Column('departmentAdminPassWord', sa.String(length=20), server_default=sa.text("'123456'"), nullable=True),
    sa.Column('admin_departmentId', sa.String(length=20), nullable=True, comment='部门ID，外键'),
    sa.Column('loginTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['admin_departmentId'], ['departments.departmentId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('departmentAdminId'),
    sa.UniqueConstraint('departmentAdminId')
    )
    op.create_table('face_value',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 外键、主键、非空、不重复'),
    sa.Column('staffFaceValue', sa.Text(), nullable=True, comment='人脸特征向量/Text任意长度字符类型'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('holiday_apply',
    sa.Column('applyId', sa.String(length=20), nullable=False, comment='请假记录ID/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/不为空'),
    sa.Column('applyMessage', sa.Text(), nullable=True, comment='申请信息'),
    sa.Column('replyMessage', sa.Text(), nullable=True, comment='批复内容'),
    sa.Column('applyTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='申请时间'),
    sa.Column('replyTime', sa.DateTime(), nullable=True, comment='批复时间'),
    sa.Column('replyId', sa.String(length=20), nullable=True, comment='批复者ID'),
    sa.Column('beginApplyDate', sa.Date(), nullable=True, comment='申请假期开始时间'),
    sa.Column('endApplyDate', sa.Date(), nullable=True, comment='申请假期结束时间'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('applyId'),
    sa.UniqueConstraint('applyId')
    )
    op.create_table('holidays',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/主键/不重复/不为空'),
    sa.Column('holidayState', sa.Boolean(), server_default='0', nullable=True, comment='休假状态'),
    sa.Column('holidayTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='剩余假期总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('outs',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/主键/外键/不重复/不为空'),
    sa.Column('outState', sa.Boolean(), server_default='0', nullable=True, comment='职工出差状态'),
    sa.Column('outTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='职工出差总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('overtime_record',
    sa.Column('addId', sa.String(length=20), nullable=False, comment='加班记录/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/主键/外键/不为空'),
    sa.Column('beginAddTime', sa.DateTime(), nullable=True, comment='加班签到时间'),
    sa.Column('endAddTime', sa.DateTime(), nullable=True, comment='加班签退时间'),
    sa.Column('workTime', sa.Float(), nullable=True, comment='加班工作时间'),
    sa.Column('addDate', sa.Date(), nullable=True, comment='加班记录日期'),
    sa.Column('beginAddImage', sa.LargeBinary(length=65536), nullable=True, comment='加班签到拍照'),
    sa.Column('endAddImage', sa.LargeBinary(length=65536), nullable=True, comment='加班签退拍照'),
    sa.Column('attendState', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='加班签到状态'),
    sa.Column('endState', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='加班签退状态'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('addId'),
    sa.UniqueConstraint('addId')
    )
    op.create_table('set',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 外键、主键、非空、不重复'),
    sa.Column('attendTime', sa.DateTime(), nullable=True, comment='应签到时间+1900-1-1'),
    sa.Column('endTime', sa.DateTime(), nullable=True, comment='应签退时间+1900-1-1'),
    sa.Column('beginAttendDate', sa.Date(), nullable=True, comment='考勤起始日期'),
    sa.Column('endAttendDate', sa.Date(), nullable=True, comment='考勤结束日期'),
    sa.Column('holidayState', sa.Boolean(), server_default='0', nullable=True, comment='请假状态/默认没有请假FALSE/不能为空'),
    sa.Column('beginHolidayDate', sa.Date(), nullable=True, comment='请假起始日期'),
    sa.Column('endHolidayDate', sa.Date(), nullable=True, comment='请假结束日期'),
    sa.Column('outState', sa.Boolean(), server_default='0', nullable=True, comment='出差状态/默认没有出差FALSE/不能为空'),
    sa.Column('beginOutDate', sa.Date(), nullable=True, comment='出差起始日期'),
    sa.Column('endOutDate', sa.Date(), nullable=True, comment='出差结束日期'),
    sa.Column('addState', sa.Boolean(), server_default='0', nullable=True, comment='加班状态/默认没有加班FALSE/不能为空'),
    sa.Column('beginAddTime', sa.DateTime(), nullable=True, comment='加班起始具体时间（年月日时分秒）/ 不设置结束时间，以结束后打卡时间为准'),
    sa.Column('updateTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='设置更新时间'),
    sa.Column('updateId', sa.String(length=20), nullable=True, comment='更新者id'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('staff_information',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID，外键、主键、不为空、不重复'),
    sa.Column('staffName', sa.String(length=20), server_default=sa.text("'未命名'"), nullable=True, comment='姓名 不允许为空'),
    sa.Column('staffGetFaceState', sa.Boolean(), server_default='0', nullable=True, comment='职工录入人脸图片权限'),
    sa.Column('staffGender', sa.String(length=20), server_default=sa.text("'性别未知'"), nullable=True, comment=' 性别 不允许为空 设置String字符串，'),
    sa.Column('staffCountry', sa.String(length=20), nullable=True, comment='国籍'),
    sa.Column('staffNation', sa.String(length=20), nullable=True, comment='民族'),
    sa.Column('staffOrigin', sa.String(length=20), nullable=True, comment='籍贯'),
    sa.Column('staffBirthday', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('staffPhoneNumber', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('staffEmailAddress', sa.String(length=30), nullable=True, comment='邮箱地址'),
    sa.Column('staffState', sa.Boolean(), server_default='1', nullable=True, comment='在职状态 不允许为空'),
    sa.Column('staffPositionId', sa.String(length=20), nullable=False, comment='岗位ID'),
    sa.Column('staffDepartmentId', sa.String(length=20), nullable=False, comment='部门ID'),
    sa.Column('staff_create_updateDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='信息创建时间/更新时间'),
    sa.Column('staff_create_updateId', sa.String(length=20), nullable=True, comment='创建/更新ID'),
    sa.Column('informationState', sa.Boolean(), server_default='0', nullable=True, comment='职工信息完善状态'),
    sa.Column('faceValueState', sa.Boolean(), server_default='0', nullable=True, comment='职工人脸信息完善状态'),
    sa.Column('staffAddress', sa.Text(), nullable=True, comment='家庭住址'),
    sa.Column('staffCheckState', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='非工作时间：0  出勤：{普通出勤：10 , 出差：11 ,  休假： 12  , 加班出勤： 13} ;   缺勤：{普通缺勤：20 , 普通迟到：21 ;  普通早退：22;  加班缺勤：23  ;  加班迟到： 24 ;  加班早退： 25}'),
    sa.Column('staff_Remark', sa.Text(), nullable=True, comment='备注/Text任意长度字符类型'),
    sa.ForeignKeyConstraint(['staffDepartmentId'], ['departments.departmentId'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['staffPositionId'], ['position.positionId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('sum',
    sa.Column('sumId', sa.String(length=20), nullable=False, comment='统计ID/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/不为空'),
    sa.Column('holidayFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='休假次数'),
    sa.Column('attendFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='出勤次数'),
    sa.Column('lateFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='迟到次数'),
    sa.Column('earlyFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='早退次数'),
    sa.Column('absenceFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='缺勤次数'),
    sa.Column('addFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='加班次数'),
    sa.Column('outFrequency', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='出差次数'),
    sa.Column('addSumTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='加班总时长'),
    sa.Column('outSumTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='出差总时长'),
    sa.Column('workSumTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='工作时长'),
    sa.Column('standardWorkSumTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='标准工作时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('sumId'),
    sa.UniqueConstraint('sumId')
    )
    op.create_table('system_apply',
    sa.Column('applyId', sa.String(length=20), nullable=False, comment='留言记录ID/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/不为空'),
    sa.Column('applyMessage', sa.Text(), nullable=True, comment='留言信息'),
    sa.Column('replyMessage', sa.Text(), nullable=True, comment='回复内容'),
    sa.Column('applyTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='留言时间'),
    sa.Column('replyTime', sa.DateTime(), nullable=True, comment='回复时间'),
    sa.Column('replyId', sa.String(length=20), nullable=True, comment='回复者ID'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('applyId'),
    sa.UniqueConstraint('applyId')
    )
    op.create_table('works',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/主键/不重复/不为空'),
    sa.Column('workState', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='工作状态'),
    sa.Column('workTime', sa.Float(), server_default=sa.text('0.0'), nullable=True, comment='工作总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('system_apply')
    op.drop_table('sum')
    op.drop_table('staff_information')
    op.drop_table('set')
    op.drop_table('overtime_record')
    op.drop_table('outs')
    op.drop_table('holidays')
    op.drop_table('holiday_apply')
    op.drop_table('face_value')
    op.drop_table('department_admin')
    op.drop_table('attendance')
    op.drop_table('adds')
    op.drop_table('system_announcement')
    op.drop_table('staff')
    op.drop_table('position')
    op.drop_table('gate_admin')
    op.drop_table('departments')
    op.drop_table('attendance_aps')
    op.drop_table('admin')
    # ### end Alembic commands ###
