"""empty message

Revision ID: 41e1ef16e93b
Revises: 09aa18ab632e
Create Date: 2023-05-07 21:54:34.060933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41e1ef16e93b'
down_revision = '09aa18ab632e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_information', 'staffGender',
               existing_type=mysql.VARCHAR(length=20),
               comment=' 性别 不允许为空 设置String字符串，',
               existing_comment=' 性别 不允许为空 设置String字符串，在前端设置为仅允许选择填入“男”、 “女”、“其他” 这三个选项',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_information', 'staffGender',
               existing_type=mysql.VARCHAR(length=20),
               comment=' 性别 不允许为空 设置String字符串，在前端设置为仅允许选择填入“男”、 “女”、“其他” 这三个选项',
               existing_comment=' 性别 不允许为空 设置String字符串，',
               existing_nullable=False)
    # ### end Alembic commands ###
