"""empty message

Revision ID: 7019fbf1fbb7
Revises: 1754f9357592
Create Date: 2023-05-09 15:37:45.879929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7019fbf1fbb7'
down_revision = '1754f9357592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_admin_ibfk_1', 'department_admin', type_='foreignkey')
    op.drop_column('department_admin', 'admin_departmentId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_admin', sa.Column('admin_departmentId', mysql.VARCHAR(length=20), nullable=True, comment='部门ID，外键'))
    op.create_foreign_key('department_admin_ibfk_1', 'department_admin', 'departments', ['admin_departmentId'], ['departmentId'], onupdate='CASCADE')
    # ### end Alembic commands ###
