"""empty message

Revision ID: 78deb0c3b3d8
Revises: 22794e1372e9
Create Date: 2023-03-21 19:17:18.641367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78deb0c3b3d8'
down_revision = '22794e1372e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_time')
    # ### end Alembic commands ###
