"""empty message

Revision ID: 7a55a03f2003
Revises: f09e11563188
Create Date: 2023-04-26 21:41:26.840639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a55a03f2003'
down_revision = 'f09e11563188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_information', 'staffImage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('staffImage', mysql.MEDIUMBLOB(), nullable=True, comment='职工用户头像图片/允许为空'))
    # ### end Alembic commands ###
