"""empty message

Revision ID: 7b168c483e4f
Revises: 96324627ac8d
Create Date: 2023-04-05 17:48:33.890202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b168c483e4f'
down_revision = '96324627ac8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_announcement',
    sa.Column('announcementId', sa.String(length=20), nullable=False, comment='公告记录ID/主键/不为空/不重复'),
    sa.Column('publishId', sa.String(length=20), nullable=True, comment='发布者ID'),
    sa.Column('publishTime', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('publishMessage', sa.Text(), nullable=True, comment='发布内容'),
    sa.PrimaryKeyConstraint('announcementId'),
    sa.UniqueConstraint('announcementId')
    )
    op.create_table('holiday_apply',
    sa.Column('applyId', sa.String(length=20), nullable=False, comment='请假记录ID/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/不为空'),
    sa.Column('applyMessage', sa.Text(), nullable=True, comment='申请信息'),
    sa.Column('replyMessage', sa.Text(), nullable=True, comment='批复内容'),
    sa.Column('applyTime', sa.DateTime(), nullable=False, comment='申请时间'),
    sa.Column('replyTime', sa.DateTime(), nullable=True, comment='批复时间'),
    sa.Column('replyId', sa.String(length=20), nullable=True, comment='批复者ID'),
    sa.Column('beginApplyDate', sa.Date(), nullable=True, comment='申请假期开始时间'),
    sa.Column('endApplyDate', sa.Date(), nullable=True, comment='申请假期结束时间'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('applyId'),
    sa.UniqueConstraint('applyId')
    )
    op.create_table('system_apply',
    sa.Column('applyId', sa.String(length=20), nullable=False, comment='留言记录ID/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/不为空'),
    sa.Column('applyMessage', sa.Text(), nullable=True, comment='留言信息'),
    sa.Column('replyMessage', sa.Text(), nullable=True, comment='回复内容'),
    sa.Column('applyTime', sa.DateTime(), nullable=False, comment='留言时间'),
    sa.Column('replyTime', sa.DateTime(), nullable=True, comment='回复时间'),
    sa.Column('replyId', sa.String(length=20), nullable=True, comment='回复者ID'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('applyId'),
    sa.UniqueConstraint('applyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_apply')
    op.drop_table('holiday_apply')
    op.drop_table('system_announcement')
    # ### end Alembic commands ###
