"""empty message

Revision ID: 7c1d3e3d8329
Revises: c316ae4751b1
Create Date: 2023-05-08 16:57:00.470117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c1d3e3d8329'
down_revision = 'c316ae4751b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_information', 'staffAge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('staffAge', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年龄'))
    # ### end Alembic commands ###
