"""empty message

Revision ID: 96324627ac8d
Revises: 33396d2e8be1
Create Date: 2023-04-05 00:48:56.903464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96324627ac8d'
down_revision = '33396d2e8be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adds',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/主键/外键/不为空/不重复'),
    sa.Column('addState', sa.Boolean(), nullable=False, comment='加班状态'),
    sa.Column('addTime', sa.Float(), nullable=False, comment='加班总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('outs',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/主键/外键/不重复/不为空'),
    sa.Column('outState', sa.Boolean(), nullable=False, comment='职工出差状态'),
    sa.Column('outTime', sa.Float(), nullable=False, comment='职工出差总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('overtime_record',
    sa.Column('addId', sa.String(length=20), nullable=False, comment='加班记录/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/主键/外键/不为空'),
    sa.Column('beginAddTime', sa.DateTime(), nullable=True, comment='加班签到时间'),
    sa.Column('endAddTime', sa.DateTime(), nullable=True, comment='加班签退时间'),
    sa.Column('workTime', sa.Float(), nullable=True, comment='加班工作时间'),
    sa.Column('addDate', sa.Date(), nullable=True, comment='加班记录日期'),
    sa.Column('beginAddImage', sa.LargeBinary(length=65536), nullable=True, comment='加班签到拍照'),
    sa.Column('endAddImage', sa.LargeBinary(length=65536), nullable=True, comment='加班签退拍照'),
    sa.Column('attendState', sa.Integer(), nullable=False, comment='加班签到状态'),
    sa.Column('endState', sa.Integer(), nullable=False, comment='加班签退状态'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('addId'),
    sa.UniqueConstraint('addId')
    )
    op.create_table('sum',
    sa.Column('sumId', sa.String(length=20), nullable=False, comment='统计ID/主键/不为空/不重复'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/不为空'),
    sa.Column('holidayFrequency', sa.Integer(), nullable=False, comment='休假次数'),
    sa.Column('attendFrequency', sa.Integer(), nullable=False, comment='出勤次数'),
    sa.Column('lateFrequency', sa.Integer(), nullable=False, comment='迟到次数'),
    sa.Column('earlyFrequency', sa.Integer(), nullable=False, comment='早退次数'),
    sa.Column('absenceFrequency', sa.Integer(), nullable=False, comment='缺勤次数'),
    sa.Column('addFrequency', sa.Integer(), nullable=False, comment='加班次数'),
    sa.Column('outFrequency', sa.Integer(), nullable=False, comment='出差次数'),
    sa.Column('addSumTime', sa.Float(), nullable=False, comment='加班总时长'),
    sa.Column('outSumTime', sa.Float(), nullable=False, comment='出差总时长'),
    sa.Column('workSumTime', sa.Float(), nullable=False, comment='工作时长'),
    sa.Column('standardWorkSumTime', sa.Float(), nullable=False, comment='标准工作时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('sumId'),
    sa.UniqueConstraint('sumId')
    )
    op.create_table('works',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/主键/不重复/不为空'),
    sa.Column('WorkState', sa.Integer(), nullable=False, comment='工作状态'),
    sa.Column('holidayTime', sa.Float(), nullable=False, comment='工作总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.alter_column('attendance', 'attendDate',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='记录日期')
    op.alter_column('attendance', 'outState',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='出差状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态,如果出差，在此记录状态，工作时间设置八小时，其余空白/出差总时长相应增加/出差次数+1',
               existing_comment='出差状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态，如果出差，在此记录状态，工作时间设置八小时，其余空白/出差总时长相应增加/出差次数+1')
    op.alter_column('attendance', 'holidayState',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='请假状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态 如果请假，在此记录状态，工作时间设置0，其余空白，请假次数+1/假期剩余总时长对应相减/',
               existing_comment='请假状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态，如果请假，在此记录状态，工作时间设置0，其余空白，请假次数+1/假期剩余总时长对应相减/')
    op.alter_column('holidays', 'holidayState',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='休假状态')
    op.alter_column('holidays', 'holidayTime',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='剩余假期总时长')
    op.add_column('set', sa.Column('beginAddTime', sa.DateTime(), nullable=True, comment='加班起始具体时间（年月日时分秒）/ 不设置结束时间，以结束后打卡时间为准'))
    op.add_column('set', sa.Column('updateTime', sa.DateTime(), nullable=False, comment='设置更时间'))
    op.add_column('set', sa.Column('updateId', sa.String(length=20), nullable=True, comment='更新者id'))
    op.drop_column('set', 'beginAddDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('beginAddDate', mysql.DATETIME(), nullable=True, comment='加班起始具体时间（年月日时分秒）/ 不设置结束时间，以结束后打卡时间为准'))
    op.drop_column('set', 'updateId')
    op.drop_column('set', 'updateTime')
    op.drop_column('set', 'beginAddTime')
    op.alter_column('holidays', 'holidayTime',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='剩余假期总时长')
    op.alter_column('holidays', 'holidayState',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='休假状态')
    op.alter_column('attendance', 'holidayState',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='请假状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态，如果请假，在此记录状态，工作时间设置0，其余空白，请假次数+1/假期剩余总时长对应相减/',
               existing_comment='请假状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态 如果请假，在此记录状态，工作时间设置0，其余空白，请假次数+1/假期剩余总时长对应相减/')
    op.alter_column('attendance', 'outState',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='出差状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态，如果出差，在此记录状态，工作时间设置八小时，其余空白/出差总时长相应增加/出差次数+1',
               existing_comment='出差状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态,如果出差，在此记录状态，工作时间设置八小时，其余空白/出差总时长相应增加/出差次数+1')
    op.alter_column('attendance', 'attendDate',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='记录日期')
    op.drop_table('works')
    op.drop_table('sum')
    op.drop_table('overtime_record')
    op.drop_table('outs')
    op.drop_table('adds')
    # ### end Alembic commands ###
