"""empty message

Revision ID: 9da11ebeb7d2
Revises: 054bd2fb0e40
Create Date: 2023-05-18 08:40:14.709321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da11ebeb7d2'
down_revision = '054bd2fb0e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_aps',
    sa.Column('attendanceApsId', sa.String(length=20), nullable=False, comment='APS 函数ID/主键/非空/唯一值'),
    sa.Column('execute_time', sa.DateTime(), nullable=True, comment='上一次执行时间'),
    sa.PrimaryKeyConstraint('attendanceApsId'),
    sa.UniqueConstraint('attendanceApsId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_aps')
    # ### end Alembic commands ###
