"""empty message

Revision ID: c5c28eda8e14
Revises: 7b168c483e4f
Create Date: 2023-04-09 13:29:42.053542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c28eda8e14'
down_revision = '7b168c483e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('positionLevel', table_name='position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('positionLevel', 'position', ['positionLevel'], unique=False)
    # ### end Alembic commands ###
