"""empty message

Revision ID: d06c64b9a04b
Revises: 39ea1d6b586c
Create Date: 2023-05-19 23:49:57.586294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd06c64b9a04b'
down_revision = '39ea1d6b586c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('leaveTime', sa.Time(), nullable=True, comment='临时离开的时间'))
    op.alter_column('staff_information', 'staffCheckState',
               existing_type=mysql.INTEGER(),
               comment='今日尚未出勤：0  出勤：{今日出勤（工作中）：10 , 今日出差：11 ,  今日休假： 12  , 加班出勤（工作中）： 13 ,  今日出勤（已完成工作） 14  加班出勤（已完成工作）15 } ;   缺勤：{今日缺勤：20 , 今日迟到（工作中）：21 ;  今日早退：22; 今日迟到（未出勤）27  今日迟到|早退 28   今日迟到（已完成工作）29   今日加班缺勤：23  ;  今日加班迟到（工作中）： 24 ; 今日加班迟到（未出勤）30 ;  }',
               existing_comment='非工作时间：0  出勤：{普通出勤：10 , 出差：11 ,  休假： 12  , 加班出勤： 13} ;   缺勤：{普通缺勤：20 , 普通迟到：21 ;  普通早退：22;  加班缺勤：23  ;  加班迟到： 24 ;  加班早退： 25}',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_information', 'staffCheckState',
               existing_type=mysql.INTEGER(),
               comment='非工作时间：0  出勤：{普通出勤：10 , 出差：11 ,  休假： 12  , 加班出勤： 13} ;   缺勤：{普通缺勤：20 , 普通迟到：21 ;  普通早退：22;  加班缺勤：23  ;  加班迟到： 24 ;  加班早退： 25}',
               existing_comment='今日尚未出勤：0  出勤：{今日出勤（工作中）：10 , 今日出差：11 ,  今日休假： 12  , 加班出勤（工作中）： 13 ,  今日出勤（已完成工作） 14  加班出勤（已完成工作）15 } ;   缺勤：{今日缺勤：20 , 今日迟到（工作中）：21 ;  今日早退：22; 今日迟到（未出勤）27  今日迟到|早退 28   今日迟到（已完成工作）29   今日加班缺勤：23  ;  今日加班迟到（工作中）： 24 ; 今日加班迟到（未出勤）30 ;  }',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('attendance', 'leaveTime')
    # ### end Alembic commands ###
