"""empty message

Revision ID: d1256cb3bb09
Revises: 7019fbf1fbb7
Create Date: 2023-05-09 15:39:17.617792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1256cb3bb09'
down_revision = '7019fbf1fbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_admin', sa.Column('admin_departmentId', sa.String(length=20), nullable=True, comment='部门ID，外键'))
    op.create_foreign_key(None, 'department_admin', 'departments', ['admin_departmentId'], ['departmentId'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department_admin', type_='foreignkey')
    op.drop_column('department_admin', 'admin_departmentId')
    # ### end Alembic commands ###
