"""empty message

Revision ID: d4f16b16efa0
Revises: dc41e6eb3088
Create Date: 2023-04-04 21:18:48.215846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f16b16efa0'
down_revision = 'dc41e6eb3088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('departmentId', sa.String(length=20), nullable=False, comment='部门ID/主键/不为空/不重复'),
    sa.Column('departmentName', sa.String(length=20), nullable=False, comment='部门名称'),
    sa.PrimaryKeyConstraint('departmentId'),
    sa.UniqueConstraint('departmentId')
    )
    op.add_column('staff_information', sa.Column('staffDepartmentId', sa.String(length=20), nullable=False, comment='部门ID'))
    op.add_column('staff_information', sa.Column('staff_create_updateId', sa.String(length=20), nullable=True, comment='创建/更新ID'))
    op.add_column('staff_information', sa.Column('informationState', sa.NullType(), nullable=True))
    op.create_foreign_key(None, 'staff_information', 'departments', ['staffDepartmentId'], ['departmentId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_information', type_='foreignkey')
    op.drop_column('staff_information', 'informationState')
    op.drop_column('staff_information', 'staff_create_updateId')
    op.drop_column('staff_information', 'staffDepartmentId')
    op.drop_table('departments')
    # ### end Alembic commands ###
