"""empty message

Revision ID: dc41e6eb3088
Revises: 
Create Date: 2023-04-03 11:45:51.777501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc41e6eb3088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.String(length=20), nullable=False, comment='系统管理员ID、主键、不为空、不重复'),
    sa.Column('adminPassWord', sa.String(length=20), nullable=False, comment='系统管理员密码 不允许为空'),
    sa.Column('loginTime', sa.DateTime(), nullable=True, comment='上次登录时间'),
    sa.PrimaryKeyConstraint('adminId'),
    sa.UniqueConstraint('adminId')
    )
    op.create_table('department_admin',
    sa.Column('departmentAdminId', sa.String(length=20), nullable=False),
    sa.Column('departmentAdminPassWord', sa.String(length=20), nullable=False),
    sa.Column('loginTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('departmentAdminId'),
    sa.UniqueConstraint('departmentAdminId')
    )
    op.create_table('gate_admin',
    sa.Column('gateAdminId', sa.String(length=20), nullable=False),
    sa.Column('gateAdminPassWord', sa.String(length=20), nullable=False),
    sa.Column('loginTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('gateAdminId'),
    sa.UniqueConstraint('gateAdminId')
    )
    op.create_table('position',
    sa.Column('positionId', sa.String(length=20), nullable=False, comment='岗位ID'),
    sa.Column('positionName', sa.String(length=20), nullable=True, comment='岗位名称'),
    sa.Column('positionLevel', sa.Integer(), nullable=True, comment='岗位等级'),
    sa.PrimaryKeyConstraint('positionId'),
    sa.UniqueConstraint('positionId'),
    sa.UniqueConstraint('positionLevel'),
    sa.UniqueConstraint('positionName')
    )
    op.create_table('staff',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 主键、不允许为空、不重复'),
    sa.Column('staffPassWord', sa.String(length=20), nullable=False, comment='职工密码 不为空'),
    sa.Column('loginTime', sa.DateTime(), nullable=True, comment='上次登录时间'),
    sa.Column('staffState', sa.Boolean(), nullable=False, comment='就职状态（默认设置为在职TRUE） 不为空'),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('attendance',
    sa.Column('attendanceId', sa.String(length=50), nullable=False, comment='出勤记录ID/主键/不重复/不为空/！！以当天Date日期+职工ID合成String作为出勤记录ID存入！！'),
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/允许重复（1对多）/不为空'),
    sa.Column('attendTime', sa.Time(), nullable=True, comment='签到打卡时间'),
    sa.Column('endTime', sa.Time(), nullable=True, comment='签退打卡时间'),
    sa.Column('workTime', sa.Time(), nullable=True, comment='工作时间'),
    sa.Column('attendDate', sa.Date(), nullable=True, comment='记录日期'),
    sa.Column('attendImage', sa.LargeBinary(length=65536), nullable=True, comment='签到拍照打卡截图'),
    sa.Column('endImage', sa.LargeBinary(length=65536), nullable=True, comment='签退拍照打卡截图'),
    sa.Column('attendState', sa.Integer(), nullable=False, comment='签到状态/默认为0未打卡/不为空/出勤1/迟到2/缺勤3'),
    sa.Column('endState', sa.Integer(), nullable=False, comment='签退状态/默认为0未打卡/不为空/早退2/晚签退3'),
    sa.Column('outState', sa.Boolean(), nullable=True, comment='出差状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态，如果出差，在此记录状态，工作时间设置八小时，其余空白/出差总时长相应增加/出差次数+1'),
    sa.Column('holidayState', sa.Boolean(), nullable=True, comment='请假状态/不设置为外键/每次生成每天的出勤记录之前检查set表的个人状态，如果请假，在此记录状态，工作时间设置0，其余空白，请假次数+1/假期剩余总时长对应相减/'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('attendanceId'),
    sa.UniqueConstraint('attendanceId')
    )
    op.create_table('face_value',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 外键、主键、非空、不重复'),
    sa.Column('staffFaceValue', sa.Text(), nullable=True, comment='人脸特征向量/Text任意长度字符类型'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('holidays',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID/外键/主键/不重复/不为空'),
    sa.Column('holidayState', sa.Boolean(), nullable=True, comment='休假状态'),
    sa.Column('holidayTime', sa.Float(), nullable=True, comment='剩余假期总时长'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('set',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID 外键、主键、非空、不重复'),
    sa.Column('attendTime', sa.DateTime(), nullable=True, comment='应签到时间'),
    sa.Column('endTime', sa.DateTime(), nullable=True, comment='应签退时间'),
    sa.Column('beginAttendDate', sa.Date(), nullable=True, comment='考勤起始日期'),
    sa.Column('endAttendDate', sa.Date(), nullable=True, comment='考勤结束日期'),
    sa.Column('holidayState', sa.Boolean(), nullable=False, comment='请假状态/默认没有请假FALSE/不能为空'),
    sa.Column('beginHolidayDate', sa.Date(), nullable=True, comment='请假起始日期'),
    sa.Column('endHolidayDate', sa.Date(), nullable=True, comment='请假结束日期'),
    sa.Column('outState', sa.Boolean(), nullable=False, comment='出差状态/默认没有出差FALSE/不能为空'),
    sa.Column('beginOutDate', sa.Date(), nullable=True, comment='出差起始日期'),
    sa.Column('endOutDate', sa.Date(), nullable=True, comment='出差结束日期'),
    sa.Column('addState', sa.Boolean(), nullable=False, comment='加班状态/默认没有加班FALSE/不能为空'),
    sa.Column('beginAddDate', sa.DateTime(), nullable=True, comment='加班起始具体时间（年月日时分秒）/ 不设置结束时间，以结束后打卡时间为准'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    op.create_table('staff_information',
    sa.Column('staffId', sa.String(length=20), nullable=False, comment='职工ID，外键、主键、不为空、不重复'),
    sa.Column('staffName', sa.String(length=20), nullable=False, comment='姓名 不允许为空'),
    sa.Column('staffGender', sa.String(length=20), nullable=False, comment=' 性别 不允许为空 设置String字符串，在前端设置为仅允许选择填入“男”、 “女”、“其他” 这三个选项'),
    sa.Column('staffCountry', sa.String(length=20), nullable=True, comment='国籍'),
    sa.Column('staffNation', sa.String(length=20), nullable=True, comment='民族'),
    sa.Column('staffAge', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('staffBirthday', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('staffPhoneNumber', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('staffEmailAddress', sa.String(length=30), nullable=True, comment='邮箱地址'),
    sa.Column('staffState', sa.Boolean(), nullable=False, comment='在职状态 不允许为空'),
    sa.Column('staffPositionId', sa.String(length=20), nullable=False, comment='岗位ID'),
    sa.Column('staff_create_updateDate', sa.DateTime(), nullable=False, comment='信息创建时间/更新时间'),
    sa.Column('staff_Remark', sa.Text(), nullable=True, comment='备注/Text任意长度字符类型'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.staffId'], ),
    sa.ForeignKeyConstraint(['staffPositionId'], ['position.positionId'], ),
    sa.PrimaryKeyConstraint('staffId'),
    sa.UniqueConstraint('staffId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_information')
    op.drop_table('set')
    op.drop_table('holidays')
    op.drop_table('face_value')
    op.drop_table('attendance')
    op.drop_table('staff')
    op.drop_table('position')
    op.drop_table('gate_admin')
    op.drop_table('department_admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
