"""empty message

Revision ID: e232a85baa80
Revises: 0f3e7a295781
Create Date: 2023-04-16 21:14:34.750946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e232a85baa80'
down_revision = '0f3e7a295781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('staffOrigin', sa.String(length=20), nullable=True, comment='籍贯'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_information', 'staffOrigin')
    # ### end Alembic commands ###
