"""empty message

Revision ID: e530c912a1f3
Revises: 7a55a03f2003
Create Date: 2023-05-05 00:26:46.199505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e530c912a1f3'
down_revision = '7a55a03f2003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('staffCheckState', sa.Integer(), nullable=True, comment='下班：0  出勤：{普通出勤：10 , 出差：11 , 休假：12} ;   缺勤：{普通缺勤：20 , 加班缺勤：21}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_information', 'staffCheckState')
    # ### end Alembic commands ###
