"""empty message

Revision ID: f09e11563188
Revises: e232a85baa80
Create Date: 2023-04-26 13:57:34.677196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09e11563188'
down_revision = 'e232a85baa80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_information', sa.Column('staffImage', sa.LargeBinary(length=65536), nullable=True, comment='职工用户头像图片/允许为空'))
    op.add_column('staff_information', sa.Column('staffGetFaceState', sa.Boolean(), nullable=False, comment='职工录入人脸图片权限'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_information', 'staffGetFaceState')
    op.drop_column('staff_information', 'staffImage')
    # ### end Alembic commands ###
